[package]
name = "Quern_cargo"
version = "0.1.0"
edition = "2021"
[dependencies]
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "chrono"] }
serde_yaml = "0.9"
regex = "1"
clap = { version = "4", features = ["derive"] }
# tokio = { version = "1", features = ["full"] }

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1