use clap::Parser;
use chrono::Local;
use std::fs;
use std::path::Path;
use std::process::Command;
use tracing::{error, info};
use tracing_subscriber::fmt::time::ChronoLocal;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::Layer; 
use uuid::Uuid;